#!/bin/bash
repositories=("origin" "upstream")
commit_message="Auto pushing"
for remote in "${remotes[@]}"
do
    echo "Pushing changes to $remote"
    git push $remote master
done
git add .
git commit -m "$commit_message"
git push origin main


